# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/tosmxx/pre-sample
    rev: v1.0.0
    hooks:
      - id: trailing-whitespace
